lib/chatty_web/router.ex
defmodule ChattyWeb.Router do
  use ChattyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChattyWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChattyWeb do
    pipe_through :browser

    get "/", RoomController, :index
    resources("/rooms", RoomController, except: [:index])
    resources("/sessions", SessionController, only: [:new, :create])
    resources "/registration", RegistrationController, only: [:new, :create]
    delete "/sign_out", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChattyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChattyWeb.Telemetry
    end
  end
end

lib/chatty_web/views/layout_view.ex
defmodule ChattyWeb.LayoutView do
  use ChattyWeb, :view
end

lib/chatty_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Chatty</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
    crossorigin="anonymous" />
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>

<body>
  <div class="min-h-screen max-w-screen max-h-screen flex flex-col">
    <header class="bg-gradient-to-r from-red-400 to-gray-700 p-4 w-full">
      <nav class="w-full p-0 flex flex-col justify-evenly md:flex-row md:justify-between  items-center">
        <div class="py-1">
          <%= link "Chatty", to: Routes.room_path(@conn, :index), class: "font-medium md:ml-4 text-xl uppercase text-red-300 tracking-widest"%>
          <i class="far fa-comments fa-lg text-red-300"></i>
        </div>
        <%= if @signed_in? do %>
        <div class="w-48 flex flex-col items-center md:w-72 md:flex-row">
          <h3 class=" p-2 text-center font-thin text-gray-100"> Signed in as :
            <%= Chatty.Accounts.current_user(@conn).username %>
          </h3>
          <div>
            <%= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :delete, class: "px-4 py-2 rounded-full text-white bg-red-400 shadow-lg" %>
            <div>
              <% else %>
              <div class="w-48">
                <%= link "Sign Up", to: Routes.registration_path(@conn, :new), class: "px-4 py-2 font-light rounded-lg text-white bg-red-400" %>
                <%= link "Log in", to: Routes.session_path(@conn, :new), class: "px-4 py-2 font-light rounded-lg text-white bg-red-400"%>
              </div>
              <% end %>
      </nav>
    </header>
    <%= unless is_nil(get_flash(@conn, :info)) do %>
    <p class="bg-red-400" role="alert"> <%= get_flash(@conn, :info) %></p>
    <% end %>
    <%= unless is_nil(get_flash(@conn, :error)) do %>
    <p class="bg-red-400" role="alert"> <%= get_flash(@conn, :error) %></p>
    <% end %>
    <main role="main" class="flex-grow bg-gray-600 flex items-center justify-center">
      <%= @inner_content %>
    </main>
    <script>
      window.userToken = "<%= assigns[:user_token] %>";
    </script>
  </div>
</body>

</html>